import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ComfortPeak Heating & Air | Furnace & AC Repair in Dallas-Fort Worth",
  description:
    "Furnace and AC repair in the Dallas-Fort Worth area. Same-day appointments, upfront pricing, licensed technicians. Call ComfortPeak Heating & Air.",
};

const htmlContent = `
<style>
:root{--ink:#14202b;--muted:#61707d;--blue:#1267d6;--blue-dark:#0b4fa9;--ice:#eef6ff;--line:#dce5ed;--white:#fff;--green:#177245;--shadow:0 18px 55px rgba(20,32,43,.10)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);background:#fff;line-height:1.6}a{text-decoration:none;color:inherit}.container{width:min(1120px,calc(100% - 40px));margin:auto}
.topbar{background:#10202d;color:#dbe7ef;font-size:13px}.topbar .container{display:flex;justify-content:space-between;gap:20px;padding:9px 0}.nav{border-bottom:1px solid var(--line);background:#fff;position:sticky;top:0;z-index:20}.nav-inner{height:74px;display:flex;align-items:center;justify-content:space-between}.logo{font-weight:800;letter-spacing:-.03em;font-size:20px}.logo span{color:var(--blue)}.navlinks{display:flex;gap:28px;color:#50606d;font-size:14px}.nav-phone{font-weight:750;color:var(--blue)}.button{display:inline-flex;align-items:center;justify-content:center;gap:8px;border-radius:8px;padding:13px 20px;font-weight:750;font-size:14px;transition:.2s}.button-primary{background:var(--blue);color:#fff;box-shadow:0 8px 22px rgba(18,103,214,.20)}.button-primary:hover{background:var(--blue-dark);transform:translateY(-1px)}.button-secondary{border:1px solid #bfcdd8;background:#fff}.button-secondary:hover{background:#f6f9fc}
.hero{background:linear-gradient(180deg,#f6faff 0%,#fff 100%);padding:86px 0 72px}.hero-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:70px;align-items:center}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.14em;font-weight:800;color:var(--blue);margin-bottom:17px}.hero h1{font-size:clamp(42px,5.5vw,68px);line-height:1.02;letter-spacing:-.055em;margin:0 0 23px;max-width:700px}.hero h1 em{font-style:normal;color:var(--blue)}.hero p{font-size:18px;color:var(--muted);max-width:620px;margin:0 0 30px}.actions{display:flex;gap:12px;flex-wrap:wrap}.microtrust{display:flex;gap:18px;flex-wrap:wrap;margin-top:24px;color:#667682;font-size:12px}.microtrust span:before{content:'✓';color:var(--green);font-weight:900;margin-right:6px}.hero-card{background:#122331;border-radius:18px;padding:12px;box-shadow:var(--shadow)}.hero-photo{min-height:440px;border-radius:11px;background:linear-gradient(135deg,#d8e7f3,#94b6cf);position:relative;overflow:hidden}.hero-photo:before{content:'';position:absolute;width:330px;height:330px;border-radius:50%;background:rgba(255,255,255,.42);right:-70px;top:-50px}.house{position:absolute;left:12%;right:12%;bottom:0;height:63%;background:#f8fafb;border-radius:8px 8px 0 0;box-shadow:0 20px 40px rgba(20,32,43,.12)}.roof{position:absolute;left:-8%;top:-70px;width:116%;height:120px;background:#263c4c;transform:skewY(-8deg);border-radius:8px}.window{position:absolute;width:82px;height:95px;background:#a8d0ec;border:8px solid #dfe7ec;top:37%;left:16%;box-shadow:120px 0 0 -8px #a8d0ec}.door{position:absolute;bottom:0;right:17%;width:82px;height:145px;background:#31566e;border-radius:5px 5px 0 0}.hvac{position:absolute;right:13%;bottom:24%;width:82px;height:64px;background:#e9eef1;border-radius:7px;box-shadow:inset 0 -8px 0 #cbd5db}.hero-label{position:absolute;left:25px;bottom:24px;background:rgba(255,255,255,.94);padding:14px 16px;border-radius:10px;box-shadow:0 12px 30px rgba(20,32,43,.14);font-size:13px}.hero-label strong{display:block;font-size:15px}
.trust{border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:#fff}.trust-grid{display:grid;grid-template-columns:repeat(4,1fr)}.trust-item{padding:23px 18px;text-align:center;border-right:1px solid var(--line);font-size:13px;font-weight:700}.trust-item:last-child{border-right:0}.trust-item small{display:block;color:#74828d;font-weight:500;margin-top:2px}
section{padding:92px 0}.section-head{max-width:720px;margin-bottom:45px}.section-head .eyebrow{margin-bottom:12px}.section-head h2{font-size:clamp(32px,4vw,48px);line-height:1.08;letter-spacing:-.045em;margin:0 0 15px}.section-head p{color:var(--muted);font-size:17px;margin:0}.problem{background:#f7fafc}.problem-grid{display:grid;grid-template-columns:.85fr 1.15fr;gap:70px;align-items:start}.problem-copy h3{font-size:27px;letter-spacing:-.025em;margin:0 0 13px}.problem-copy p{color:var(--muted)}.symptoms{display:grid;grid-template-columns:1fr 1fr;gap:12px}.symptom{background:#fff;border:1px solid var(--line);padding:20px;border-radius:11px}.symptom strong{display:block;margin-bottom:5px}.symptom span{font-size:13px;color:var(--muted)}
.services-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.service{border:1px solid var(--line);border-radius:13px;padding:26px;background:#fff;min-height:210px}.service .num{color:var(--blue);font-size:12px;font-weight:800;letter-spacing:.1em}.service h3{font-size:20px;margin:35px 0 8px}.service p{font-size:13px;color:var(--muted);margin:0}.why{background:#122331;color:#fff}.why .section-head p{color:#b7c6d0}.why-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.why-card{border:1px solid rgba(255,255,255,.14);border-radius:13px;padding:28px;background:rgba(255,255,255,.035)}.why-card h3{margin:0 0 9px;font-size:19px}.why-card p{margin:0;color:#b7c6d0;font-size:14px}
.process-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.step{border-top:2px solid #d4e0ea;padding-top:20px}.step .number{font-size:12px;font-weight:800;color:var(--blue)}.step h3{font-size:18px;margin:10px 0 7px}.step p{font-size:13px;color:var(--muted);margin:0}.area{background:#eef6ff}.area-grid{display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:center}.area h2{font-size:42px;line-height:1.08;letter-spacing:-.045em;margin:0 0 15px}.area p{color:var(--muted)}.area-box{background:#fff;border:1px solid #d8e6f2;border-radius:14px;padding:28px}.area-box strong{display:block;margin-bottom:13px}.chips{display:flex;flex-wrap:wrap;gap:8px}.chip{padding:8px 11px;border:1px solid var(--line);border-radius:99px;font-size:12px;color:#52636f}
.faq-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.faq{border:1px solid var(--line);border-radius:11px;padding:22px}.faq h3{font-size:16px;margin:0 0 8px}.faq p{font-size:13px;color:var(--muted);margin:0}.cta{padding:75px 0}.cta-box{background:#eaf4ff;border:1px solid #d5e7f7;border-radius:18px;padding:55px;display:flex;justify-content:space-between;align-items:center;gap:40px}.cta h2{font-size:42px;line-height:1.08;letter-spacing:-.045em;margin:0 0 10px}.cta p{color:var(--muted);margin:0;max-width:600px}.cta-actions{display:flex;flex-direction:column;gap:9px;min-width:190px}.cta-actions .button{text-align:center}.footer{background:#10202d;color:#aebdc7;padding:38px 0}.footer-grid{display:flex;justify-content:space-between;gap:30px}.footer strong{color:#fff}.footer small{font-size:11px;display:block;margin-top:10px;max-width:700px;line-height:1.5}

.call-strip{background:#fff7e8;border-bottom:1px solid #f0dfbc}.call-strip .container{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:13px 0;font-size:13px}.call-strip strong{color:#7b4d00}.call-strip a{font-weight:800;color:var(--blue)}
.hero .eyebrow{letter-spacing:.1em}.hero h1{max-width:650px}.hero p{max-width:580px}.hero-proof{display:flex;gap:14px;align-items:center;margin-top:20px;font-size:12px;color:#667682}.hero-proof b{color:var(--ink)}
.hero-photo{background:linear-gradient(145deg,#dceaf4,#9abbd0)}
.section-head h2{max-width:780px}.service-primary{border-color:#a9cbed;box-shadow:0 10px 30px rgba(18,103,214,.08);position:relative}.service-primary:after{content:'Most requested';position:absolute;top:18px;right:18px;background:#eaf4ff;color:var(--blue);font-size:10px;font-weight:800;padding:5px 8px;border-radius:99px}.service-primary h3{margin-top:35px}
.callout{background:#f7fafc;border:1px solid var(--line);border-radius:14px;padding:28px;margin-top:22px}.callout strong{display:block;margin-bottom:6px}.callout p{margin:0;color:var(--muted);font-size:14px}
.form-section{background:#fff}.contact-grid{display:grid;grid-template-columns:.85fr 1.15fr;gap:60px;align-items:start}.contact-copy h2{font-size:42px;line-height:1.08;letter-spacing:-.045em;margin:0 0 14px}.contact-copy p{color:var(--muted)}.contact-points{margin-top:25px;display:grid;gap:13px}.contact-point{display:flex;gap:11px;font-size:14px}.contact-point span{color:var(--blue);font-weight:900}.service-form{border:1px solid var(--line);border-radius:16px;padding:30px;box-shadow:var(--shadow);background:#fff}.service-form h3{margin:0 0 5px;font-size:22px}.service-form>p{margin:0 0 22px;color:var(--muted);font-size:13px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{display:grid;gap:6px}.field.full{grid-column:1/-1}.field label{font-size:12px;font-weight:750}.field input,.field select,.field textarea{width:100%;border:1px solid #cbd7e0;border-radius:8px;padding:12px 13px;font:inherit;font-size:14px;background:#fff;color:var(--ink)}.field textarea{min-height:105px;resize:vertical}.form-note{font-size:11px!important;color:#7b8790!important;margin:11px 0 0!important}.service-form .button{width:100%;border:0;cursor:pointer;margin-top:16px}
.mobile-call{display:none}.proof-slot{margin-top:20px;border:1px dashed #9db6cc;border-radius:10px;padding:11px 14px;font-size:12px;color:#5b6d7a;background:#f6faff;max-width:520px}.proof-slot b{color:var(--ink)}
@media(max-width:850px){.contact-grid{grid-template-columns:1fr}.call-strip .container{padding:11px 0}.hero-proof{flex-wrap:wrap}.mobile-call{display:flex;position:fixed;bottom:0;left:0;right:0;z-index:50;background:#fff;padding:9px 12px;border-top:1px solid var(--line);box-shadow:0 -8px 25px rgba(20,32,43,.10)}.mobile-call a{flex:1}.footer{padding-bottom:80px}}
@media(max-width:560px){.call-strip .container{display:block;text-align:center}.call-strip a{display:inline-block;margin-top:3px}.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.contact-copy h2{font-size:34px}}
@media(max-width:850px){.navlinks{display:none}.hero-grid,.problem-grid,.area-grid{grid-template-columns:1fr}.hero{padding-top:60px}.hero-card{max-width:620px}.trust-grid,.services-grid,.process-grid{grid-template-columns:1fr 1fr}.why-grid,.faq-grid{grid-template-columns:1fr}.cta-box{padding:35px;display:block}.cta-actions{margin-top:25px;flex-direction:row}.cta-actions .button{flex:1}.area h2{font-size:34px}}
@media(max-width:560px){.container{width:min(100% - 28px,1120px)}.topbar .container{display:block;text-align:center}.nav-inner{height:65px}.nav-phone{display:none}.hero{padding:48px 0}.hero h1{font-size:42px}.hero p{font-size:16px}.hero-photo{min-height:350px}.trust-grid,.services-grid,.process-grid{grid-template-columns:1fr}.trust-item{border-right:0;border-bottom:1px solid var(--line)}.trust-item:last-child{border-bottom:0}.symptoms{grid-template-columns:1fr}.cta{padding:45px 0}.cta-box{padding:28px}.cta h2{font-size:34px}.cta-actions{display:flex;flex-direction:column}.footer-grid{display:block}}
</style>
<div class="topbar"><div class="container"><span>Residential heating &amp; air in the Dallas–Fort Worth area</span><span>Open 7 days • Evening appointments available</span></div></div>
<header class="nav"><div class="container nav-inner"><a class="logo" href="#top">Comfort<span>Peak</span></a><nav class="navlinks"><a href="#services">Services</a><a href="#process">How It Works</a><a href="#faq">FAQ</a></nav><a class="nav-phone" href="tel:+12145550184">(214) 555-0184</a></div></header>
<main id="top">
<div class="call-strip"><div class="container"><span><strong>No heat or no cooling?</strong> Same-day appointments available. Call now.</span><a href="tel:+12145550184">(214) 555-0184 →</a></div></div>
<section class="hero"><div class="container hero-grid"><div><div class="eyebrow">Dallas–Fort Worth • Heating &amp; Air</div><h1>Furnace not working? <em>Get it fixed today.</em></h1><p>Call now and we'll send a licensed technician as soon as today. You'll know the price before any work begins.</p><div class="actions"><a class="button button-primary" href="tel:+12145550184">Call (214) 555-0184 →</a><a class="button button-secondary" href="#contact">Request same-day service</a></div><div class="microtrust"><span>Licensed &amp; insured</span><span>Upfront pricing</span><span>Open 7 days</span></div><div class="proof-slot"><b>Reviews go here.</b> A live page shows the company's real Google rating and review count next to the call button.</div></div><div class="hero-card"><div class="hero-photo"><div class="house"><div class="roof"></div><div class="window"></div><div class="door"></div><div class="hvac"></div></div><div class="hero-label"><strong>No heat tonight?</strong>Call now. A technician can be at your door today.</div></div></div></div></section>
<div class="trust"><div class="container trust-grid"><div class="trust-item">Licensed &amp; insured<small>License number shown on every page</small></div><div class="trust-item">Upfront pricing<small>Approve the price before work starts</small></div><div class="trust-item">Open 7 days<small>Evening and weekend appointments</small></div><div class="trust-item">Heating and AC<small>Furnaces, heat pumps, air conditioners</small></div></div></div>
<section class="problem"><div class="container problem-grid"><div class="problem-copy"><div class="eyebrow">When your system quits</div><h3>You don't need to diagnose it yourself.</h3><p>Cold house or hot house, the first step is the same: tell us what the system is doing. We'll find the cause and quote the fix before we start.</p><a class="button button-primary" href="tel:+12145550184">Talk to a technician →</a></div><div class="symptoms"><div class="symptom"><strong>Furnace won't turn on</strong><span>No heat, or the system won't start at all.</span></div><div class="symptom"><strong>Blowing cold air</strong><span>The furnace runs, but the house isn't warming up.</span></div><div class="symptom"><strong>Banging or rattling</strong><span>Loud, new noises from the furnace or vents.</span></div><div class="symptom"><strong>AC not cooling</strong><span>Warm air, weak airflow or water around the unit.</span></div></div></div></section>
<section id="services"><div class="container"><div class="section-head"><div class="eyebrow">What we fix</div><h2>Heating and cooling help for the problem in front of you.</h2><p>Furnace repair is our most requested service right now. We also repair AC and replace systems that are past saving.</p></div><div class="services-grid"><div class="service service-primary"><div class="num">01</div><h3>Furnace &amp; Heating Repair</h3><p>Furnaces and heat pumps that won't start, won't heat, or keep shutting off.</p></div><div class="service"><div class="num">02</div><h3>AC Repair</h3><p>Warm air, weak airflow, leaks and noises. Diagnosed and repaired.</p></div><div class="service"><div class="num">03</div><h3>System Replacement</h3><p>When repair no longer makes sense, we explain your options and quote the replacement.</p></div><div class="service"><div class="num">04</div><h3>Seasonal Tune-Ups</h3><p>A yearly check to catch problems before they leave you without heat or cooling.</p></div></div></div></section>
<section class="why"><div class="container"><div class="section-head"><div class="eyebrow">Why homeowners call us</div><h2>When your home is uncomfortable, you want a straight answer.</h2><p>Here's what to expect when you call.</p></div><div class="why-grid"><div class="why-card"><h3>Upfront pricing</h3><p>You approve the price before any repair starts. No surprises on the invoice.</p></div><div class="why-card"><h3>Licensed, insured technicians</h3><p>Residential specialists who explain the problem in plain English.</p></div><div class="why-card"><h3>Honest repair-or-replace advice</h3><p>If a repair makes sense, we'll say so. If replacement is smarter, we'll show you both numbers.</p></div></div></div></section>
<section id="process"><div class="container"><div class="section-head"><div class="eyebrow">The process</div><h2>From phone call to warm house.</h2><p>Four steps, no runaround.</p></div><div class="process-grid"><div class="step"><div class="number">01 / CALL</div><h3>Tell us what's happening</h3><p>Call or send a request. Tell us the symptoms and your ZIP code.</p></div><div class="step"><div class="number">02 / BOOK</div><h3>Pick a time</h3><p>We confirm an arrival window, same day when available.</p></div><div class="step"><div class="number">03 / DIAGNOSE</div><h3>Know the cost first</h3><p>The technician finds the cause and quotes the repair before starting.</p></div><div class="step"><div class="number">04 / FIX</div><h3>Back to comfortable</h3><p>Approve the work, and we get your heat or cooling running again.</p></div></div></div></section>
<section class="area"><div class="container area-grid"><div><div class="eyebrow">Service area</div><h2>Serving homeowners across Dallas–Fort Worth.</h2><p>Not sure we cover your neighborhood? Call and ask. We'll tell you right away.</p></div><div class="area-box"><strong>Cities we serve</strong><div class="chips"><span class="chip">Dallas</span><span class="chip">Fort Worth</span><span class="chip">Arlington</span><span class="chip">Irving</span><span class="chip">Plano</span><span class="chip">Frisco</span><span class="chip">Grand Prairie</span><span class="chip">Richardson</span></div></div></div></section>
<section id="faq"><div class="container"><div class="section-head"><div class="eyebrow">Questions homeowners ask</div><h2>Before you call, here's what you may want to know.</h2></div><div class="faq-grid"><div class="faq"><h3>How fast can someone come out?</h3><p>Call before 3 PM for same-day service in most of DFW. Evening and weekend appointments are available.</p></div><div class="faq"><h3>What does a service call cost?</h3><p>The diagnostic fee is quoted when you book, and you approve any repair price before work begins.</p></div><div class="faq"><h3>Should I repair or replace?</h3><p>If the system is 12–15+ years old and the repair costs a large share of a new unit, replacement can make more sense. We'll give you both numbers so you can decide.</p></div><div class="faq"><h3>Do you work on both heating and AC?</h3><p>Yes. Furnaces, heat pumps and air conditioners in homes. We don't do commercial systems.</p></div></div></div></section>
<section class="form-section" id="contact"><div class="container contact-grid"><div class="contact-copy"><div class="eyebrow">Request service</div><h2>Tell us what your heat or AC is doing.</h2><p>Prefer not to call? Send a short request and we'll call you back to confirm a time.</p><div class="contact-points"><div class="contact-point"><span>01</span><div><strong>Describe the issue</strong><br>No heat, cold air, noises, leaks, or something else.</div></div><div class="contact-point"><span>02</span><div><strong>Add your ZIP code</strong><br>So we can confirm we serve your area and find the soonest time.</div></div><div class="contact-point"><span>03</span><div><strong>We call you back</strong><br>A team member confirms an arrival window and the diagnostic fee.</div></div></div></div><form class="service-form" onsubmit="event.preventDefault(); alert('Demo form — in a live deployment this would send the lead to the HVAC company.');"><h3>Request same-day service</h3><p>Demo form for the NorthDemand portfolio project.</p><div class="form-grid"><div class="field"><label for="name">Name</label><input id="name" required placeholder="Your name"></div><div class="field"><label for="phone">Phone</label><input id="phone" type="tel" required placeholder="(555) 555-5555"></div><div class="field full"><label for="zip">ZIP code</label><input id="zip" inputmode="numeric" pattern="[0-9]{5}" maxlength="5" required placeholder="75201"></div><div class="field full"><label for="service">What do you need help with?</label><select id="service"><option>No heat / furnace won't start</option><option>Blowing cold air</option><option>AC not cooling</option><option>Strange noise</option><option>Water / leaking</option><option>Replacement quote</option><option>Other HVAC issue</option></select></div><div class="field full"><label for="message">Tell us what's happening</label><textarea id="message" placeholder="Example: The furnace clicks but never starts, and the house is getting cold."></textarea></div></div><button class="button button-primary" type="submit">Request same-day service →</button><p class="form-note">Demo only. No information is submitted or stored from this portfolio page.</p></form></div></section>
</main>
<footer class="footer"><div class="container footer-grid"><div><strong>ComfortPeak Heating &amp; Air</strong><small>Demonstration project created by NorthDemand to show a conversion-focused landing page for residential HVAC lead generation. ComfortPeak is fictional. Hours, license, pricing, warranty and offers shown are example placeholders; a live page would use the company's real details, license number and customer reviews.</small></div><div><small>Dallas–Fort Worth, Texas<br>Demo phone: (214) 555-0184<br>Demo email: service@comfortpeak-demo.com</small></div></div></footer>
<div class="mobile-call"><a class="button button-primary" href="tel:+12145550184">Call now for heating &amp; AC repair →</a></div>
`;

export default function ComfortPeakLandingPage() {
  return (
    <div dangerouslySetInnerHTML={{ __html: htmlContent }} />
  );
}
